#!/usr/bin/env bash
set -euo pipefail

TEST_FILE="src/testFunctions.gs"
ENABLE_API_KEY_TESTS="${ENABLE_API_KEY_TESTS:-false}"
ENABLE_VERTEX_AI_TESTS="${ENABLE_VERTEX_AI_TESTS:-false}"
OPEN_AI_API_KEY="${OPEN_AI_API_KEY:-}"
GEMINI_API_KEY="${GEMINI_API_KEY:-}"
VERTEX_AI_PROJECT_ID="${VERTEX_AI_PROJECT_ID:-}"
VERTEX_AI_LOCATION="${VERTEX_AI_LOCATION:-global}"

if [ ! -f "$TEST_FILE" ]; then
  echo "::error::${TEST_FILE} not found; cannot prepare remote Apps Script tests."
  exit 1
fi

if [ "$ENABLE_API_KEY_TESTS" = "true" ]; then
  missing=()
  if [ -z "$OPEN_AI_API_KEY" ]; then
    missing+=("OPEN_AI_API_KEY")
  fi
  if [ -z "$GEMINI_API_KEY" ]; then
    missing+=("GEMINI_API_KEY")
  fi

  if [ "${#missing[@]}" -gt 0 ]; then
    printf '::error::Cannot prepare API key tests because required environment variable(s) are missing: %s\n' "${missing[*]}"
    exit 1
  fi
else
  echo "Skipping API key injection: API key tests are disabled."
fi

if [ "$ENABLE_VERTEX_AI_TESTS" = "true" ]; then
  if [ -z "$VERTEX_AI_PROJECT_ID" ]; then
    echo "::error::Cannot prepare Vertex AI tests because VERTEX_AI_PROJECT_ID is missing."
    exit 1
  fi
else
  echo "Skipping Vertex AI configuration injection: Vertex AI tests are disabled."
fi

tmp_file="$(mktemp)"
node <<'NODE' > "$tmp_file"
const declarations = {
  OPEN_AI_API_KEY: process.env.OPEN_AI_API_KEY || '',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
  VERTEX_AI_PROJECT_ID: process.env.VERTEX_AI_PROJECT_ID || '',
  VERTEX_AI_LOCATION: process.env.VERTEX_AI_LOCATION || 'global',
};

for (const [name, value] of Object.entries(declarations)) {
  process.stdout.write(`const ${name} = ${JSON.stringify(value)};\n`);
}
NODE

cat "$TEST_FILE" >> "$tmp_file"
mv "$tmp_file" "$TEST_FILE"

if [ "$ENABLE_VERTEX_AI_TESTS" = "true" ]; then
  cat >> "$TEST_FILE" <<'EOF_VERTEX_TEST'

// Generated by .github/scripts/prepare-tests.sh for CI-only Vertex AI remote test execution.
function testVertexAISimpleChat() {
  GenAIApp.setGeminiAuth(VERTEX_AI_PROJECT_ID, VERTEX_AI_LOCATION);
  const chat = GenAIApp.newChat();
  chat.addMessage("Reply with exactly: Vertex AI test passed");
  const response = chat.run({ model: GEMINI_MODEL, max_tokens: 64 });
  if (String(response).trim() !== "Vertex AI test passed") {
    throw new Error(`Unexpected Vertex AI response: ${response}`);
  }
  console.log(`Vertex AI simple chat response:\n${response}`);
}
}
EOF_VERTEX_TEST
fi

echo "Prepared ${TEST_FILE} for remote Apps Script tests."
